# Generated by Django 4.1 on 2023-11-23 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="busAllocations",
            fields=[
                ("busNumber", models.IntegerField(primary_key=True, serialize=False)),
                ("garage", models.CharField(max_length=50)),
                ("artic", models.BooleanField(default=False)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Bus Allocations",
            },
        ),
        migrations.CreateModel(
            name="routes",
            fields=[
                ("routeNumber", models.IntegerField(primary_key=True, serialize=False)),
                ("routeName", models.CharField(max_length=100)),
                ("artic", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Routes",
            },
        ),
        migrations.CreateModel(
            name="routeAllocations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("garage", models.CharField(max_length=50)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.routes"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Route Allocations",
            },
        ),
    ]
