# Generated by Django 4.1 on 2023-11-23 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routeallocations",
            name="route",
            field=models.ForeignKey(
                db_column="route",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.routes",
            ),
        ),
    ]
