# Generated by Django 4.1 on 2023-11-23 02:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_routeallocations_route"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="routeallocations",
            unique_together={("route", "garage")},
        ),
    ]
