# Generated by Django 4.1 on 2023-11-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_routeallocations_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routeallocations",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
