# Generated by Django 4.1 on 2023-11-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_routeallocations_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routeallocations",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
