# Generated by Django 4.1 on 2023-11-24 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_routeallocations_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="specialSightings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("busGarage", models.CharField(max_length=50)),
                ("routeGarage", models.CharField(max_length=50)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "busNumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.busallocations",
                    ),
                ),
                (
                    "routeNumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.routes"
                    ),
                ),
            ],
        ),
    ]
