# Generated by Django 4.1 on 2024-01-07 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_specialsightings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialsightings",
            options={"verbose_name_plural": "Special Sightings"},
        ),
        migrations.RenameField(
            model_name="specialsightings",
            old_name="routeGarage",
            new_name="runGarage",
        ),
        migrations.RenameField(
            model_name="specialsightings",
            old_name="routeNumber",
            new_name="runNumber",
        ),
    ]
