# Generated by Django 4.1 on 2024-01-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_specialsightings_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialsightings",
            name="busGarage",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="specialsightings",
            name="runGarage",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="specialsightings",
            name="runNumber",
            field=models.CharField(max_length=20),
        ),
    ]
