# Generated by Django 4.1 on 2024-01-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_specialsightings_busgarage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialsightings",
            name="runGarage",
            field=models.CharField(max_length=100),
        ),
    ]
